INSERT INTO coach_sites (
  id,
  coach_id,
  coach_name,
  slug,
  status,
  niche,
  location,
  bio,
  vision,
  coach_email,
  coach_phone,
  whatsapp_link,
  photo_url,
  logo_url,
  video_url,
  google_form_url,
  hero_media_type,
  public_url,
  register_button_text,
  selected_theme_id,
  support_text,
  content_json,
  analytics_json,
  created_at,
  updated_at,
  published_at,
  archived_at,
  created_by,
  updated_by
) VALUES (
  'coach-site-gyana-ranjan',
  'coach-gyana',
  'Gyana Ranjan',
  'gyana-ranjan',
  'published',
  'PMOS / Women Wellness',
  'Odisha',
  'Practical wellness coach helping women understand hormones and daily lifestyle routines.',
  'Make hormone education calmer, practical, and easier to follow alongside medical guidance.',
  '',
  '',
  '',
  '/images/coach-gyana-ranjan.png',
  '',
  'https://www.youtube.com/embed/gBQoms47fB8?playsinline=1&controls=1&rel=0&modestbranding=1',
  '',
  'image',
  '/coach/gyana-ranjan',
  'Register Now',
  'default-current',
  '',
  '{"heroHeadline":"Meet Gyana Ranjan for practical PMOS lifestyle guidance.","subheadline":"A fixed-template coach referral page introducing the coach, niche, vision, and next registration step.","coachIntro":"Gyana helps women slow down confusing hormone advice and rebuild simple routines around food, movement, sleep, stress, and tracking.","visionText":"Support women with education-first guidance that fits real life and works alongside medical advice when needed.","benefits":["Understand common lifestyle patterns connected to PMOS symptoms.","Get a calmer view of food, movement, sleep, and routine consistency.","Know the right next step before joining a deeper program."],"ctaText":"Register Now","faq":[{"question":"Is this medical treatment?","answer":"No. This coach page is for education and lifestyle guidance only."},{"question":"What happens after registration?","answer":"The register button opens the admin-provided Google Form when configured."}],"trustText":"Education-first, doctor-friendly coaching support. This does not replace diagnosis or treatment.","socialCopy":"Join Gyana Ranjan''s PMOS lifestyle guidance page for a clear first step."}',
  '{"averageVisits":0,"conversionRate":"0%","dailyVisits":0,"deviceBreakdown":{"desktop":0,"mobile":0,"tablet":0},"lastUpdated":"Not connected","monthlyVisits":0,"region":"Not available","source":"Not available","totalRegisterClicks":0,"totalVisits":0,"totalWhatsappClicks":0,"videoPlays":0,"weeklyVisits":0}',
  CAST(strftime('%s', 'now') AS INTEGER),
  CAST(strftime('%s', 'now') AS INTEGER),
  CAST(strftime('%s', 'now') AS INTEGER),
  NULL,
  'codex-production-import',
  'codex-production-import'
)
ON CONFLICT(slug) DO UPDATE SET
  coach_id = excluded.coach_id,
  coach_name = excluded.coach_name,
  status = excluded.status,
  niche = excluded.niche,
  location = excluded.location,
  bio = excluded.bio,
  vision = excluded.vision,
  coach_email = excluded.coach_email,
  coach_phone = excluded.coach_phone,
  whatsapp_link = excluded.whatsapp_link,
  photo_url = excluded.photo_url,
  logo_url = excluded.logo_url,
  video_url = excluded.video_url,
  google_form_url = excluded.google_form_url,
  hero_media_type = excluded.hero_media_type,
  public_url = excluded.public_url,
  register_button_text = excluded.register_button_text,
  selected_theme_id = excluded.selected_theme_id,
  support_text = excluded.support_text,
  content_json = excluded.content_json,
  analytics_json = excluded.analytics_json,
  updated_at = excluded.updated_at,
  published_at = COALESCE(coach_sites.published_at, excluded.published_at),
  archived_at = NULL,
  updated_by = excluded.updated_by;
